# Use the official Node.js 18 image as a base image
FROM node:18

# Set the working directory inside the container
WORKDIR ./

# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Copy .env file
COPY .env .env

# Build the TypeScript files
RUN npm run build

# Expose the port the app runs on
EXPOSE 8080

# Start the application
CMD ["npm", "start"]

